Add GHA build
seqeralabs/xpack-dnanexus pull request #2
Opened 2021-03-25 17:54 UTC by pditommaso

This PR adds the GH action test for Nextflow app for DX. It can serve also a space for app files review.

2021-03-26 04:29 UTC, commandlinegirl requested changes
Minor comments.

2021-03-26 13:37 UTC, pditommaso commented on .github/workflows/build.yml
> +      - name: Install java
Well spotted

2021-03-26 13:37 UTC, pditommaso commented on .github/workflows/build.yml
> +          sudo apt-get install -y apt-transport-https wget git openssh-server tree python3 python3-pip python3-venv
Correct

2021-03-29 20:40 UTC, commandlinegirl requested changes
Thank you for addressing the reviews. Here are my comments.

2021-03-29 20:40 UTC, commandlinegirl commented on src/dxapp.json
> +    "file": "dxapp.sh",
Please point "file" to `src/dxapp.sh` once adjusting the app source directory structure

2021-03-29 20:40 UTC, commandlinegirl commented on src/dxapp.json
> +        "help": "Provide Nextflow run arguments & pipeline parameters using ",
```suggestion
        "help": "(Optional) Provide Nextflow run arguments & pipeline parameters. ",
```

2021-03-29 20:40 UTC, commandlinegirl commented on src/dxapp.json
> +        "help": "Enable launcher script debug mode setting this field to 'true'",
```suggestion
        "help": "(Optional) Enable launcher script debug mode by setting this field to 'true'.",
```

2021-03-29 20:40 UTC, commandlinegirl commented on src/dxapp.json
> +        "help": "Nextflow command line options",
```suggestion
        "help": "(Optional) Nextflow command line options.",
```

2021-03-29 20:40 UTC, commandlinegirl commented on src/dxapp.json
> +        "help": "A DNAnexus storage file where the Nextflow execution log should be saved.",
```suggestion
        "help": "(Optional) A DNAnexus storage file where the Nextflow execution log should be saved.",
```

2021-03-29 20:40 UTC, commandlinegirl commented on src/dxapp.json
> +        "help": "The Nextflow session ID or resume a pipeline execution.",
```suggestion
        "help": "(Optional) The Nextflow session ID or resume a pipeline execution.",
```

2021-03-29 20:40 UTC, commandlinegirl commented on src/dxapp.json
> +        "help": "The work directory used by Nextflow for scratch data. If provided it must be a DNAnexus storage path starting with 'dx://' protocol prefix",
```suggestion
        "help": "(Optional) The work directory used by Nextflow for scratch data. If provided it must be a DNAnexus storage path starting with 'dx://' protocol prefix, for example dx://PROJECT-0123456789:/some/work/dir.",
```

2021-03-29 20:40 UTC, commandlinegirl commented on src/dxapp.json
> +        "licenseUrl": "https://github.com/apache/groovy/blob/master/LICENSE",
```suggestion
        "licenseUrl": "https://github.com/apache/groovy/blob/GROOVY_3_0_7/LICENSE",
```

2021-03-29 20:40 UTC, commandlinegirl commented on src/README.md
> +### Input parameters
Please move this section under `## What are the input files?`. Thank you!

2021-03-29 20:40 UTC, commandlinegirl commented on src/README.md
> +* resume_id: The unique ID of the Nextflow execution to be resumes (optional)
```suggestion
* resume_id: The unique ID of the Nextflow execution to be resumed (optional)
```

2021-03-29 20:40 UTC, commandlinegirl commented on src/dxapp.json
> +}
One more comment regarding the `src/dxapp.sh` script. Please remove printing of the license value in debug mode. Thank you.

2021-03-29 20:40 UTC, commandlinegirl commented on src/README.md
> +Learn more at https://nextflow.io
```suggestion
Learn more at [https://nextflow.io](https://nextflow.io).
```

2021-03-29 20:40 UTC, commandlinegirl commented on src/README.md
> +
The result of running the app is that a pipeline is created and executed in the project? If so, please kindly add it for clarity. Thank you

2021-03-29 20:40 UTC, commandlinegirl commented on src/dxapp.json
> +        "class": "string",
Our convention is that a license is usually provided in a file, which is read by the app script. This way its value is not printed in the UI in the `Show Inputs/Outputs` section, which would be a security concern. Would it be possible to change the string to file for `license`?

One more comment regarding the `src/dxapp.sh` script. Please remove printing of the license value in debug mode. Thank you.

2021-03-30 14:14 UTC, pditommaso commented on src/README.md
> +Nextflow is workflow manager that enables scalable and reproducible scientific workflows using software containers.
Thanks. Done c6fcab5

2021-03-30 14:21 UTC, pditommaso commented on src/README.md
> +# Nextflow for DNAnexus Platform
I guess also this path should be updated, then 

https://github.com/seqeralabs/xpack-dnanexus/blob/a25a6717cc12ebe0c8b94af3adef7c420627e337/src/dxapp.json#L98

2021-03-30 14:36 UTC, pditommaso commented on src/dxapp.json
> +        "licenseUrl": "https://github.com/nextflow-io/nextflow/blob/master/COPYING",
Well, the NF license does not change across versions. I'd prefer to keep the master one to avoid to avoid to update each time we change NF version

2021-03-30 14:36 UTC, pditommaso commented on src/dxapp.json
> +    "file": "dxapp.sh",
ok

2021-03-30 14:40 UTC, pditommaso commented on src/dxapp.json
> +        "licenseUrl": "https://github.com/apache/groovy/blob/master/LICENSE",
Also here, it would be preferable to keep the master

2021-03-30 14:41 UTC, pditommaso commented on src/dxapp.json
> +        "help": "Enable launcher script debug mode setting this field to 'true'",
ok

2021-03-30 14:41 UTC, pditommaso commented on src/dxapp.json
> +        "help": "A DNAnexus storage file where the Nextflow execution log should be saved.",
ok

2021-03-30 14:41 UTC, pditommaso commented on src/dxapp.json
> +        "help": "The Nextflow session ID or resume a pipeline execution.",
ok

2021-03-30 14:48 UTC, pditommaso commented on src/README.md
> +# Nextflow for DNAnexus Platform
ok, done

2021-03-30 14:48 UTC, pditommaso commented on src/dxapp.json
> +        "help": "Nextflow command line options",
ok

2021-03-30 14:48 UTC, pditommaso commented on src/dxapp.json
> +        "help": "The work directory used by Nextflow for scratch data. If provided it must be a DNAnexus storage path starting with 'dx://' protocol prefix",
ok

2021-03-30 15:07 UTC, pditommaso commented on src/README.md
> +### Input parameters
I've updated this section to make it clear.

2021-03-30 15:30 UTC, pditommaso commented on src/README.md
> +
Not sure it's correct to say the *a pipeline is created in the project*. I'll tried to expand that period to make it more clear.

2021-03-30 15:32 UTC, pditommaso commented on src/dxapp.json
> +        "class": "string",
>  Would it be possible to change the string to file for license?

This would require some changes on NF side. I think we can consider this as an improvement to be addressed during the beta phase, and keep in this form at this stage.

2021-03-30 15:34 UTC, pditommaso commented on src/dxapp.json
> +}
This should solve 0d84f8f

2021-03-30 15:58 UTC, DNxEnterprise commented on src/README.md
> +
@commandlinegirl  The nextflow app does not compile the NF workflow into a DNAnexus applet or workflow within the project.  It manages the execution logic of the NF workflow.

2021-03-30 17:19 UTC, commandlinegirl commented on src/dxapp.json
> +        "licenseUrl": "https://github.com/nextflow-io/nextflow/blob/master/COPYING",
OK

2021-03-30 17:19 UTC, commandlinegirl commented on src/dxapp.json
> +        "licenseUrl": "https://github.com/apache/groovy/blob/master/LICENSE",
SG.

2021-03-30 17:19 UTC, commandlinegirl commented on src/README.md
> +
Got it, thanks for the clarification!

2021-03-30 17:22 UTC, commandlinegirl commented on src/dxapp.json
> +        "class": "string",
Yes, that can be done later.

2021-03-30 17:25 UTC, commandlinegirl approved these changes
LGTM, thank you for addressing the comments! Only a minor typo-related thing found. Thanks!

2021-03-30 17:25 UTC, commandlinegirl commented on app/dxapp.json
> +        "help": "The work directory used by Nextflow for scratch data. If provided it must be a DNAnexus storage path starting with 'dx://' protocol prefix, , for example dx://PROJECT-0123456789:/som
Minor: 
```suggestion
        "help": "The work directory used by Nextflow for scratch data. If provided it must be a DNAnexus storage path starting with 'dx://' protocol prefix, for example dx://PROJECT-0123456789:/some/work/dir (optional).",
```

2021-03-30 17:30 UTC, pditommaso commented
Awesome! merged the last suggestion! thanks a lot for the detailed review!

2021-03-30 17:30 UTC, merged