Bump dnanexus app 1.0.0-beta.6
seqeralabs/xpack-dnanexus pull request #22
Opened 2021-10-18 14:44 UTC by pditommaso

- Add the support for Nextflow resume on DNAnexus 
- Allow only files stored in a DX project for Seqera licence certificate

2021-11-02 06:49 UTC, pditommaso commented on README.md
> +- Version `1.0.0-beta.4` adds the support for Nextflow resume feature.
This is subtle, the version of the plugin used by NF is `1.0.0-beta.4`. The app published to DX is `1.0.0-beta.6`.

2021-11-02 08:38 UTC, XingGemini commented
@commandlinegirl  Could you review?

2021-11-03 04:16 UTC, commandlinegirl requested changes
This is a partial review with a few suggestions and I will be continuing to read into this tomorrow. Thanks!

2021-11-03 04:16 UTC, commandlinegirl commented on README.md
> +The best practice to store XPACK license and any other credentials files consists creating a project on dedicated DNAnexus project to upload and store safely those files. Once this project is created
A more general question: wouldn't it be easier to convert the license file input from `string` to `file` type? This would make the app more user friendly since the user wouldn't have to type the DNAnexus path, and it'd be super easy running the app from the UI.

2021-11-03 04:16 UTC, commandlinegirl commented on README.md
> +if you want to be able to resume the pipeline execution is a successive execution.
```suggestion
if you want to be able to resume the pipeline execution in a successive execution.
```

2021-11-03 04:16 UTC, commandlinegirl commented on README.md
> +Moreover input files stored into a file system other than the DNAnexus storage,
```suggestion
Moreover input files are stored into a file system other than the DNAnexus storage, 
```

2021-11-03 04:16 UTC, commandlinegirl commented on README.md
> +The ability of resume pipeline executions is a core Nextflow
```suggestion
The ability to resume pipeline executions is a core Nextflow 
```

2021-11-03 04:16 UTC, commandlinegirl commented on README.md
> +execution. Note: make sure to enable the *delay workspace destruction* feature
Would it be possible to add this note also the ap[/Readme.md so that the user that actually runs the app knows this?

Or maybe add a validation and print a message when the app is run that it will not be possible to resume afterwards since delay workspace destruction was not set (BTW job inputs are available in [/home/dnanexus/job_inputs.json](https://documentation.dnanexus.com/developer/apps/execution-environment#special-files-in-the-initial-working-directory)). Also, note that the container is kept for ca 72 hours longer so it won't be possible to resume after that time.

2021-11-05 04:32 UTC, commandlinegirl requested changes
Thank you for the update to the app with new functionality! I've got a few suggestions and found a few typos. Thanks!

2021-11-05 04:32 UTC, commandlinegirl commented on app/README.md
> +* docker_creds_file: Docker registries credentials file (optional)
Would it be possible to add an info to app/Readme on what is the expected format of the json, otherwise the user might not know how to prepare this file.

2021-11-05 04:32 UTC, commandlinegirl commented on README.md
> +execution. Note: make sure to enable the *delay workspace destruction* feature
After reading further I realized the delayed workspace destruction is needed to download the files. Another possibility you might want to consider, that doesn't require to keep the containers running for so long, is to have an explicit input on the app like `cache` and when it is True to simply upload the files to the project _before_ the job finishes. It seems it will be easier to understand for users than an enigmatic `--delay-workspace-construction`, which you don't control from the app. 

Also, is the log file always uploaded when the `--delay-workspace-construction` option is not used?

2021-11-05 04:32 UTC, commandlinegirl commented on app/README.md
> +* resume_id: The execution Id of the pipeline run to be resumed (optional)
Please mention where the user will find the resume ID of the previous run (in the job log?)

2021-11-05 08:09 UTC, XingGemini commented on README.md
> +The best practice to store XPACK license and any other credentials files consists creating a project on dedicated DNAnexus project to upload and store safely those files. Once this project is created
Using the `string` type is intentional.  Using a string as the input for the license file can prevent the file to be cloned in the job container so that it can avoid unauthorized people accessing the license file.

2021-11-05 17:17 UTC, pditommaso commented on app/README.md
> +* docker_creds_file: Docker registries credentials file (optional)
Ok, added a section at the bottom

2021-11-05 17:25 UTC, pditommaso commented on README.md
> +execution. Note: make sure to enable the *delay workspace destruction* feature
Is it possible to use the `--delay-workspace-destruction` option when launching the app via UI. Actually, I've never seen this. 

> Another possibility you might want to consider, that doesn't require to keep the containers running for so long, is to have an explicit input on the app like cache and when it is True to simply upload the files to the project before the job finishes. 

This would require moving terabyte of data for medium-large execution. Don't think is a feasible option

2021-11-05 17:25 UTC, pditommaso commented on app/README.md
> +* resume_id: The execution Id of the pipeline run to be resumed (optional)
done

2021-11-09 04:20 UTC, commandlinegirl commented on README.md
> +execution. Note: make sure to enable the *delay workspace destruction* feature
> Is it possible to use the `--delay-workspace-destruction` option when launching the app via UI. Actually, I've never seen this.

Right, it's not possible to do it from the UI.

> > Another possibility you might want to consider, that doesn't require to keep the containers running for so long, is to have an explicit input on the app like cache and when it is True to simply upload the files to the project before the job finishes.
> 
> This would require moving terabyte of data for medium-large execution. Don't think is a feasible option

But isn't it uploaded to the project here:
https://github.com/seqeralabs/xpack-dnanexus/blob/8983e2d1e22f0c7e751765665fc955a13238b546/app/src/dxapp.sh#L14?

2021-11-09 16:00 UTC, pditommaso commented on README.md
> +execution. Note: make sure to enable the *delay workspace destruction* feature
Um, it would make sense to add `--delay-workspace-destruction` including also a test for the caching, but currently there isn't. 

I'll suggest with the current version, and I'll add an issue to add the test in next iteration

2021-11-09 18:26 UTC, commandlinegirl approved these changes
LGTM modulo a few typos in the app's Readme as pointed out.

2021-11-09 18:26 UTC, commandlinegirl commented on app/README.md
> +specify the file path an an input parameter of the Nextflow app using the `scm_file`
```suggestion
specify the file path as an input parameter of the Nextflow app using the `scm_file`
```

2021-11-09 18:26 UTC, commandlinegirl commented on app/README.md
> +The access of Docker images hosted on private registry is supported providing the
```suggestion
The access of Docker images hosted in a private registry is supported by providing the
```

2021-11-09 18:44 UTC, merged