Version beta 2.1
seqeralabs/xpack-dnanexus pull request #8
Opened 2021-04-14 20:15 UTC by pditommaso

- Fix support for legacy docker runtime not supporting cpus option
- Fix close of log file on app termination
- Remove unused input fields
- Run integration test using docker

2021-04-15 16:12 UTC, commandlinegirl requested changes

2021-04-16 16:39 UTC, pditommaso commented on app/dxapp.json
> -      {
OK

2021-04-16 16:42 UTC, pditommaso commented on app/dxapp.json
> -        "name": "resume_id",
These options have been temporarily removed from the JSON inputs definition until we don't solve the technical issue to make it work. For this reason, I agree to remove these from the readme however it would be better to keep in in the app script since the plan is to make them work in an upcoming release.

2021-04-16 16:42 UTC, pditommaso commented on app/dxapp.json
> -        "name": "opts",
as above

2021-04-16 18:22 UTC, commandlinegirl requested changes

2021-04-19 08:46 UTC, pditommaso commented on app/dxapp.json
>    "details": {
Make sense. Done bb5bc47

2021-04-19 18:04 UTC, commandlinegirl reviewed
A minor issue with the `whatsNew` formatting.

2021-04-19 18:04 UTC, commandlinegirl commented on app/dxapp.json
> +    "whatsNew": "* 1.0.0-beta.2.1: Fix issue with Docker container CPUs settings; Remove unused input parameters. * 1.0.0-beta.2: First version of the Nextflow for DNAnexus"
Looks good, please add "\n" after parameters."

```"whatsNew": "* 1.0.0-beta.2.1: Fix issue with Docker container CPUs settings; Remove unused input parameters. \n* 1.0.0-beta.2: ...```

2021-04-19 19:04 UTC, pditommaso commented on app/dxapp.json
> +    "whatsNew": "* 1.0.0-beta.2.1: Fix issue with Docker container CPUs settings; Remove unused input parameters. * 1.0.0-beta.2: First version of the Nextflow for DNAnexus"
Oops 865b282

2021-04-19 19:10 UTC, commandlinegirl commented on app/dxapp.json
> +    "whatsNew": "* 1.0.0-beta.2.1: Fix issue with Docker container CPUs settings;\nRemove unused input parameters. * 1.0.0-beta.2: First version of the Nextflow for DNAnexus"
The newline should actually go after the entry for the particular version. It's a minor thing but will increase readability of the app's page in the UI. Thank you!

```suggestion
    "whatsNew": "* 1.0.0-beta.2.1: Fix issue with Docker container CPUs settings; Remove unused input parameters.\n* 1.0.0-beta.2: First version of the Nextflow for DNAnexus"
```

2021-04-19 19:12 UTC, pditommaso commented on app/dxapp.json
> +    "whatsNew": "* 1.0.0-beta.2.1: Fix issue with Docker container CPUs settings;\nRemove unused input parameters. * 1.0.0-beta.2: First version of the Nextflow for DNAnexus"
I see 😬 Thanks!

2021-04-19 19:20 UTC, commandlinegirl approved these changes
LGTM, thank you!

2021-04-19 20:01 UTC, pditommaso commented
Nice thanks

2021-04-19 20:01 UTC, merged